Repository zigpy/zha-device-handlers, pull requests merged in 2025-08, with the labels that each got.

#4226 Fix replacing Inovelli VZM35-SN clusters
  zhaquirks/inovelli/VZM35SN.py
Labels: bugfix, smash

#4239 Silence swapped direction warning for Aqara devices
  pyproject.toml
  tests/test_xiaomi.py
  zhaquirks/xiaomi/__init__.py
Labels: bugfix

#4241 Manage dependencies with uv
  .pre-commit-config.yaml
  .vscode/settings.default.json
  README.md
  pyproject.toml
  requirements_test.txt
  script/setup
  tox.ini
  uv.lock
Labels: smash, needs review

#4257 Fix SYMFONISK v2 remote quirk automation triggers
  zhaquirks/ikea/__init__.py
  zhaquirks/ikea/symfonisk2.py
Labels: bugfix

#4052 Add Bosch control relay II (BMCT-SLC / RBSH-MMS-ZB-EU)
  zhaquirks/bosch/relay_rbsh-mms-zb-eu.py
Labels: smash

#2808 Add Bosch Radiator Thermostat 2 (RBSH-TRV0-ZB-EU) quirk
  tests/test_bosch.py
  zhaquirks/bosch/rbsh_rth0_zb_eu.py
  zhaquirks/bosch/rbsh_trv0_zb_eu.py
Labels: smash, v2 quirk

#4259 Verify that no quirks do suspicious moves or copy/pastes of clusters
  tests/test_quirks.py
Labels: smash, code quality

#4256 Add Tuya valve SGW08 `_TZE284_fhvpaltk` variant
  zhaquirks/tuya/tuya_valve.py
Labels: Tuya

#4254 Add Tuya cover `_TZE200_fctwhugx` variant
  zhaquirks/tuya/ts0601_cover.py
Labels: Tuya

#4202 Add Aqara Dimmer Switch H2 EU support
  zhaquirks/xiaomi/__init__.py
  zhaquirks/xiaomi/aqara/switch_agl011.py
Labels: Xiaomi, needs review

#4287 Move XBee replacement endpoints to ZHA profile
  zhaquirks/xbee/xbee3_io.py
  zhaquirks/xbee/xbee_io.py
Labels: bugfix

#4286 Add various Tuya device variants
  zhaquirks/tuya/ts0601_dimmer.py
  zhaquirks/tuya/ts0601_power.py
  zhaquirks/tuya/ts0601_switch.py
Labels: Tuya, needs review
